version: "3"

services:
  potgres:
    image: postgres:15.4-bookworm
    ports:
      - "5432:5432"
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-password
    secrets:
      - postgres-password
    volumes:
      - postgres-data:/var/lib/postgresql/data

secrets:
  postgres-password:
    file: .secrets/postgres-password.txt

volumes:
  postgres-data:
